// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Gin-server-text/internal/biz"
	"Gin-server-text/internal/conf"
	"Gin-server-text/internal/data"
	"Gin-server-text/internal/server"
	"Gin-server-text/internal/service"
	"Gin-server-text/internal/service_gin"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedis(confData, logger)
	db := data.NewMysql(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, client, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	ginRepo := data.NewGinRepo(dataData, logger)
	ginUsecase := biz.NewGinUseCase(logger, ginRepo)
	greeterService := service.NewGreeterService(greeterUsecase, ginUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	ginUseCase := service_gin.NewGinUseCase(greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger, ginUseCase)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
